services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage

  mcp-nos:
    build:
      context: .
      dockerfile: ./mcp/mcp-nos/Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - qdrant

  openwebui:
    build: ./openwebui
    ports:
      - "3000:8080"
    environment:
      - OPENAI_API_BASE_URL=http://llm_gateway:8000/v1
      - MCP_ENDPOINTS_NOS=http://mcp-nos:8001
    depends_on:
      - llm_gateway
      - mcp-nos

  llm_gateway:
    build: ./llm_gateway
    ports:
      - "8000:8000"
    environment:
      - HF_LLAMA_70B=${HF_LLAMA_70B}
      - HF_QWEN_3_235B=${HF_QWEN_3_235B}
      - HF_API_KEY=${HF_API_KEY}
      - LITELLM_CONFIG_PATH=/app/litellm_config.yaml

  scraper:
    build: ./scraper
    volumes:
      - scraped_data_volume:/app/data
    command: ["python", "run_all.py"]

  embedding:
    build: ./embedding
    volumes:
      - scraped_data_volume:/app/data   # ← same mount as scraper!
    command: ["python", "embed_and_store.py"]
    depends_on:
      - scraper
      - qdrant

volumes:
  scraped_data_volume: