volumes:
  scraped_data_volume:

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage

  openwebui:
    build: ./openwebui
    ports:
      - "3000:8080"
    environment:
      - API_BASE_URL=http://llm_gateway:8000
      - OLLAMA_BASE_URL=""
    depends_on:
      - rag-api
      - llm_gateway

  rag-api:
    build: ./rag_api
    ports:
      - "5000:5000"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - OPENAI_API_BASE=http://llm_gateway:8000/v1
      - OPENAI_API_KEY=dummy_key
      - LLM_MODEL_NAME=custom_huggingface_model
    depends_on:
      - qdrant
      - llm_gateway

  llm_gateway:
    build: ./llm_gateway
    ports:
      - "8000:8000"
    environment:
      - LLM_GATEWAY_HF_MODEL_ID=${LLM_GATEWAY_HF_MODEL_ID}
      - HF_API_KEY=${HF_API_KEY}
      - LITELLM_CONFIG_PATH=/app/litellm_config.yaml

  scraper:
    build: ./scraper
    volumes:
      - scraped_data_volume:/app/data
    command: ["python", "run_all.py"]

  embedding:
    build: ./embedding
    volumes:
      - scraped_data_volume:/data
    command: ["python", "embed_and_store.py"]
    depends_on:
      - scraper
      - qdrant
