environment_variables:
  HF_LLAMA_70B: ${HF_LLAMA_70B}
  HF_QWEN_3_235B: ${HF_QWEN_3_235B}
  HF_API_KEY: ${HF_API_KEY}

model_list:
  - model_name: "os.environ/HF_LLAMA_70B"
    litellm_params:
      model: "os.environ/HF_LLAMA_70B"
      api_key: "os.environ/HF_API_KEY"

  - model_name: "os.environ/HF_QWEN_3_235B"
    litellm_params:
      model: "os.environ/HF_QWEN_3_235B"
      api_key: "os.environ/HF_API_KEY"

litellm_settings:
  drop_params: True

router_settings:
  pass_openai_headers: True
